# config.py

#可把此參數替還成其他伺服器或是DC的名稱，請參考universalis.app的API文件
server = "Typhon"

LAST_HISTORY_LIMIT = 50
BATCH_SIZE = 200
MAX_WORKERS = 12

MIN_PRICE = 300
MAX_PRICE = 5_000_000

WEIGHT_LIQUIDITY = 3.2
WEIGHT_STABILITY = 3.5
WEIGHT_ANTI_SPIKE = 2.5
WEIGHT_PRICE = 1.2